[package]
name = "quickheap"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
dary_heap = "0.3.7"
fastrand = "2.3.0"
fibonacci_heap = "0.7.5"
indexset = "0.12.3"
itertools = "0.14.0"
orx-priority-queue = "1.7.0"
pheap = "0.3.0"
radix-heap = "0.4.2"
rand = "0.9.2"
random = "0.14.0"
wide = "0.7.33"

[features]
u64 = []
